# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/KTD/Desktop/JYD2025_Contest-rv32i/digital_twin.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KTD/Desktop/JYD2025_Contest-rv32i/digital_twin.gen/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/KTD/Desktop/JYD2025_Contest-rv32i/digital_twin.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KTD/Desktop/JYD2025_Contest-rv32i/digital_twin.gen/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
