# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/.Xil/Vivado-22192-LAPTOP-TNKPRGBT/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tffg900-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/DRAM}
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/IROM}
  } D:/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -sv -include {
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/DRAM}
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/IROM}
  } {
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/defines.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/ACTL.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/ALU.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/CCTL.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/CSR.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/Control.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/IMMGEN.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/Mask.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/NPC.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/PC.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/RF.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/counter.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/display_seg.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/dram_driver.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/myCPU.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/perip_bridge.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/seg7.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/student_top.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/twin_controller.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/uart.sv}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/new/top.sv}
    }
      rt::read_verilog -include {
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/DRAM}
    {c:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.gen/sources_1/ip/IROM}
  } {
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/.Xil/Vivado-22192-LAPTOP-TNKPRGBT/realtime/DRAM_stub.v}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/.Xil/Vivado-22192-LAPTOP-TNKPRGBT/realtime/IROM_stub.v}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/.Xil/Vivado-22192-LAPTOP-TNKPRGBT/realtime/pll_stub.v}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/MuxKey.v}
      {C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/digital_twin.srcs/sources_1/imports/new/MuxKeyInternal.v}
    }
      rt::read_vhdl -lib xpm D:/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/KTD/Desktop/JYD2025_Contest -rv32i-error/.Xil/Vivado-22192-LAPTOP-TNKPRGBT/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
