@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 26 11:59:19 +0800 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_myCPU_func_synth -key {Post-Synthesis:sim_1:Functional:tb_myCPU} -tclbatch tb_myCPU.tcl -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_uart_behav.wcfg -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_top_behav.wcfg -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_myCPU_behav.wcfg -log simulate.log"
call xsim  tb_myCPU_func_synth -key {Post-Synthesis:sim_1:Functional:tb_myCPU} -tclbatch tb_myCPU.tcl -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_uart_behav.wcfg -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_top_behav.wcfg -view C:/Users/KTD/Desktop/JYD2025_Contest-rv32i-error/digital_twin.srcs/sim_1/imports/JYD2025_Contest-rv32i-error/tb_myCPU_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
