# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_code/digital_twin/digital_twin.srcs/sources_1/ip/DRAM1/DRAM1.xci
# IP: The module: 'DRAM1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/digital_twin/digital_twin.gen/sources_1/ip/DRAM1/DRAM1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Vivado_code/digital_twin/digital_twin.srcs/sources_1/ip/DRAM1/DRAM1.xci
# IP: The module: 'DRAM1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_code/digital_twin/digital_twin.gen/sources_1/ip/DRAM1/DRAM1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DRAM1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
